name: Gerar APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Criar APK
        uses: giuliandb/web-to-apk-action@v2
        with:
          root_dir: ./
          entry_file: index.html
          app_name: Kazin_Tecnico_2026
          package_name: br.com.kazin.jogo
          version_code: 29
          version_name: "2026.V29"

      - name: Salvar APK
        uses: actions/upload-artifact@v4
        with:
          name: APK_DO_JOGO
          path: app-release.apk
          
          
          
          
